// <auto-generated />
using System;
using System.Collections.Generic;
using MajstorHub.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MajstorHub.Api.Data.Migrations
{
    [DbContext(typeof(MajstorHubDbContext))]
    [Migration("20260818080330_AddServiceCategoryTranslations")]
    partial class AddServiceCategoryTranslations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MajstorHub.Api.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CraftsmanProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<List<string>>("PhotoUrls")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'");

                    b.Property<decimal?>("PriceQuote")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTimeOffset?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ServiceCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CraftsmanProfileId");

                    b.HasIndex("ServiceCategoryId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("MajstorHub.Api.Models.ChatbotConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Mode")
                        .IsUnique();

                    b.ToTable("ChatbotConversations");
                });

            modelBuilder.Entity("MajstorHub.Api.Models.ChatbotMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.ToTable("ChatbotMessages");
                });

            modelBuilder.Entity("MajstorHub.Api.Models.CraftsmanProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AddressText")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("BusinessName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<Point>("Location")
                        .HasColumnType("geography (point, 4326)");

                    b.Property<int>("ServiceCategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("ServiceCategoryId");

                    b.ToTable("CraftsmanProfiles");
                });

            modelBuilder.Entity("MajstorHub.Api.Models.Favorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CraftsmanProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CraftsmanProfileId");

                    b.HasIndex("ClientUserId", "CraftsmanProfileId")
                        .IsUnique();

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("MajstorHub.Api.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.HasIndex("BookingId", "CreatedAt");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MajstorHub.Api.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("CraftsmanProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("CraftsmanProfileId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("MajstorHub.Api.Models.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DescriptionMk")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DescriptionSq")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameMk")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameSq")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("SuggestedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NameEn")
                        .IsUnique();

                    b.HasIndex("SuggestedByUserId");

                    b.ToTable("ServiceCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescriptionEn = "Electrical installation and repair",
                            DescriptionMk = "Монтажа и поправка на електрична инсталација",
                            DescriptionSq = "Instalim dhe riparim i instalimeve elektrike",
                            IsApproved = true,
                            NameEn = "Electrician",
                            NameMk = "Електричар",
                            NameSq = "Elektricist"
                        },
                        new
                        {
                            Id = 2,
                            DescriptionEn = "Plumbing installation and repair",
                            DescriptionMk = "Монтажа и поправка на водоводна инсталација",
                            DescriptionSq = "Instalim dhe riparim i instalimeve hidraulike",
                            IsApproved = true,
                            NameEn = "Plumber",
                            NameMk = "Водоинсталатер",
                            NameSq = "Hidraulik"
                        },
                        new
                        {
                            Id = 3,
                            DescriptionEn = "Woodwork and furniture",
                            DescriptionMk = "Столарски работи и мебел",
                            DescriptionSq = "Punime druri dhe mobilje",
                            IsApproved = true,
                            NameEn = "Carpenter",
                            NameMk = "Столар",
                            NameSq = "Marangoz"
                        },
                        new
                        {
                            Id = 4,
                            DescriptionEn = "Interior and exterior painting",
                            DescriptionMk = "Молерисување - внатрешно и надворешно",
                            DescriptionSq = "Lyerje e brendshme dhe e jashtme",
                            IsApproved = true,
                            NameEn = "Painter",
                            NameMk = "Молер",
                            NameSq = "Bojaxhi"
                        },
                        new
                        {
                            Id = 5,
                            DescriptionEn = "Home and office cleaning",
                            DescriptionMk = "Чистење на дом и канцеларии",
                            DescriptionSq = "Pastrim shtëpie dhe zyre",
                            IsApproved = true,
                            NameEn = "Cleaner",
                            NameMk = "Чистач",
                            NameSq = "Pastrues"
                        });
                });

            modelBuilder.Entity("MajstorHub.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HouseNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Street")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MajstorHub.Api.Models.Booking", b =>
                {
                    b.HasOne("MajstorHub.Api.Models.User", "Client")
                        .WithMany("BookingsAsClient")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MajstorHub.Api.Models.CraftsmanProfile", "CraftsmanProfile")
                        .WithMany("Bookings")
                        .HasForeignKey("CraftsmanProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MajstorHub.Api.Models.ServiceCategory", "ServiceCategory")
                        .WithMany()
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("CraftsmanProfile");

                    b.Navigation("ServiceCategory");
                });

            modelBuilder.Entity("MajstorHub.Api.Models.ChatbotConversation", b =>
                {
                    b.HasOne("MajstorHub.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MajstorHub.Api.Models.ChatbotMessage", b =>
                {
                    b.HasOne("MajstorHub.Api.Models.ChatbotConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("MajstorHub.Api.Models.CraftsmanProfile", b =>
                {
                    b.HasOne("MajstorHub.Api.Models.ServiceCategory", "ServiceCategory")
                        .WithMany("CraftsmanProfiles")
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MajstorHub.Api.Models.User", "User")
                        .WithOne("CraftsmanProfile")
                        .HasForeignKey("MajstorHub.Api.Models.CraftsmanProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MajstorHub.Api.Models.Favorite", b =>
                {
                    b.HasOne("MajstorHub.Api.Models.User", "ClientUser")
                        .WithMany()
                        .HasForeignKey("ClientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MajstorHub.Api.Models.CraftsmanProfile", "CraftsmanProfile")
                        .WithMany()
                        .HasForeignKey("CraftsmanProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientUser");

                    b.Navigation("CraftsmanProfile");
                });

            modelBuilder.Entity("MajstorHub.Api.Models.Message", b =>
                {
                    b.HasOne("MajstorHub.Api.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MajstorHub.Api.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("MajstorHub.Api.Models.Review", b =>
                {
                    b.HasOne("MajstorHub.Api.Models.Booking", "Booking")
                        .WithOne("Review")
                        .HasForeignKey("MajstorHub.Api.Models.Review", "BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MajstorHub.Api.Models.CraftsmanProfile", "CraftsmanProfile")
                        .WithMany("Reviews")
                        .HasForeignKey("CraftsmanProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MajstorHub.Api.Models.User", "Reviewer")
                        .WithMany("ReviewsWritten")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("CraftsmanProfile");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("MajstorHub.Api.Models.ServiceCategory", b =>
                {
                    b.HasOne("MajstorHub.Api.Models.User", "SuggestedByUser")
                        .WithMany()
                        .HasForeignKey("SuggestedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SuggestedByUser");
                });

            modelBuilder.Entity("MajstorHub.Api.Models.Booking", b =>
                {
                    b.Navigation("Review");
                });

            modelBuilder.Entity("MajstorHub.Api.Models.ChatbotConversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("MajstorHub.Api.Models.CraftsmanProfile", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("MajstorHub.Api.Models.ServiceCategory", b =>
                {
                    b.Navigation("CraftsmanProfiles");
                });

            modelBuilder.Entity("MajstorHub.Api.Models.User", b =>
                {
                    b.Navigation("BookingsAsClient");

                    b.Navigation("CraftsmanProfile");

                    b.Navigation("ReviewsWritten");
                });
#pragma warning restore 612, 618
        }
    }
}
